# 基于官方node的镜像，做java 和maven 环境
FROM colorcoding/compiling:ibas-gtf-alpine
# 作者
MAINTAINER zhanhaibin

# 定义变量
ENV IBAS=/srv/ibas/

#初始化定义变量
RUN mkdir -p "${IBAS}" 

# 拷贝配置文件
COPY "builds.sh" "${IBAS}"
COPY "compile_order.txt" "${IBAS}"
COPY "compiles.sh" "${IBAS}"
COPY "git-ibas.sh" "${IBAS}"
COPY "git-ibas-framework.sh" "${IBAS}"
COPY "git-ibas-cloud.sh" "${IBAS}"
COPY "compile_cloud_order.txt" "${IBAS}"
COPY "deploy_wars.sh" "${IBAS}"
COPY "settings.xml" "${IBAS}"
COPY "git-btulz.transforms.sh" "${IBAS}"

RUN cp "${IBAS}"settings.xml /usr/share/java/maven-3/conf/


