# 基于nginx:alpine镜像的ibas镜像
# OS：alpine
FROM nginx:alpine

# 作者
MAINTAINER zhanhaibin 

# 安装工具
RUN set -x \
# 更新源
    && apk update \
# 安装解压、网络请求
    && apk add --no-cache unzip curl wget \
# 删除源
    && rm -rf /var/cache/apk/*