# escape=`
# 基于[windows server core]镜像
FROM colorcoding/tomcat:ibas-wincore

# 维护者
LABEL maintainer="zhanhaibin"


# 拷贝程序包
ADD ["packages/Windows.tar.gz", "C:/"]
ADD ["packages/SqlNativeClient.tar.gz", "C:/packages/"]
ADD ["packages/Prerequisites.tar", "C:/packages/"]
ADD ["packages/DI API.tar", "C:/packages/"]
ADD ["packages/SLDAgentMSI_x64.tar", "C:/packages/"]
ADD ["packages/haohua-CA/","C:/packages/haohua-CA/"]

# 使用Powershell
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# 安装证书
RUN Import-PfxCertificate -FilePath 'C:\packages\haohua-CA\keystore.pfx' -CertStoreLocation Cert:\LocalMachine\Root -Password (ConvertTo-SecureString -String "avatech" -Force –AsPlainText) ;`
    Import-Certificate -FilePath 'C:\packages\haohua-CA\myCA.cer' -CertStoreLocation Cert:\LocalMachine\Root ;`
    Import-Certificate -FilePath 'C:\packages\haohua-CA\ClientCert.crt' -CertStoreLocation Cert:\LocalMachine\CA ;

# 安装DI程序包
RUN Start-Process -FilePath msiexec -ArgumentList "/i",'C:\packages\Prerequisites\ISSetupPrerequisites\{9B88FC3F-9777-47F9-BDAB-B669D7A7E821}\vcredist.msi',"/qn" -Wait -NoNewWindow -PassThru; `
    Start-Process -FilePath msiexec -ArgumentList "/i",'C:\packages\sqlncli_x86.msi',"/qn","IACCEPTSQLNCLILICENSETERMS=YES" -Wait -NoNewWindow -PassThru; `
    Start-Process -FilePath msiexec -ArgumentList "/i",'C:\packages\sqlncli_x64.msi',"/qn","IACCEPTSQLNCLILICENSETERMS=YES" -Wait -NoNewWindow -PassThru; `
    Start-Process -FilePath 'C:\packages\Prerequisites\ISSetupPrerequisites\{8A102FA5-9E73-477b-8937-2ED4C06AF304}\vcredist_x64.exe' -ArgumentList "/q" -Wait -NoNewWindow -PassThru; `
    Start-Process -FilePath 'C:\packages\Prerequisites\ISSetupPrerequisites\{83960519-644A-4722-BA7A-37D23C1D004F}\vcredist_x86.exe' -ArgumentList "/q" -Wait -NoNewWindow -PassThru; `
    Start-Process -FilePath 'C:\packages\Prerequisites\ISSetupPrerequisites\{C4366B56-BE8F-41DA-AEFC-CB5165ADB5D3}\NDP452-KB2901907-x86-x64-AllOS-ENU.exe' -ArgumentList "/q" -Wait -NoNewWindow -PassThru; `
    Start-Process -FilePath 'C:\packages\DI API\setup.exe' -ArgumentList "/S","/v/qn" -Wait -NoNewWindow -PassThru;

# 安装SLD程序包	
RUN	Start-Process -FilePath msiexec -ArgumentList "/i",'C:\packages\SLDAgentMSI_x64\ISSetupPrerequisites\{66EE9CF0-7792-49B6-81E1-EDCC77B800B3}\msodbcsql.msi',"/qn","IACCEPTMSODBCSQLLICENSETERMS=YES" -Wait -NoNewWindow -PassThru; `
    Start-Process -FilePath msiexec -ArgumentList "/i",'C:\packages\SLDAgentMSI_x64\ISSetupPrerequisites\{5D5FFF39-015A-4DC8-A97F-6D51BAE90EDC}\SAPJVM8_x64.msi',"/qn","IACCEPTSQLNCLILICENSETERMS=YES" -Wait -NoNewWindow -PassThru; `
    Start-Process -FilePath 'C:\packages\SLDAgentMSI_x64\ISSetupPrerequisites\{57bcd1d4-2de9-49d9-bc0c-3f4263e9970e}\WindowsInstaller-KB893803-v2-x86.exe' -ArgumentList "/q" -Wait -NoNewWindow -PassThru; `
    Start-Process -FilePath 'C:\packages\SLDAgentMSI_x64\ISSetupPrerequisites\{C29E74A6-5565-44A4-AC93-A25720D76AAA}\vcredist_x64.exe' -ArgumentList "/q" -Wait -NoNewWindow -PassThru; `
    Start-Process -FilePath 'C:\packages\SLDAgentMSI_x64\ISSetupPrerequisites\{83960519-644A-4722-BA7A-37D23C1D004F}\vcredist_x86.exe' -ArgumentList "/q" -Wait -NoNewWindow -PassThru; `
    Start-Process -FilePath 'C:\packages\SLDAgentMSI_x64\SLDAgent_x64.exe' -ArgumentList "/S","/v/qn" -Wait -NoNewWindow -PassThru;

COPY ["packages/conf/", "C:/apache-tomcat-8.5.35/conf/"];
COPY ["packages/hosts", "C:/Windows/System32/drivers/etc/"];
COPY ["packages/b1-local-machine.xml", "C:/Program Files/SAP/SAP Business One DI API/Conf/"];
COPY ["packages/regSLDaddress.ps1", "C:/packages/"];
COPY ["packages/sboapi.jar", "C:/apache-tomcat-8.5.35/ibas_lib/"];
COPY ["packages/sbowrapper.jar" ,"C:/apache-tomcat-8.5.35/ibas_lib/"];

# 注册SAP SLDAddress
RUN powershell -executionpolicy unrestricted C:\packages\regSLDaddress.ps1	 ;
# 删除程序包
SHELL ["cmd", "/S", "/C"]
RUN RD /S /Q "C:/packages/"
