# 基于colorcoding/compiling:ibas-gtf-alpine镜像
FROM colorcoding/compiling:ibas-gtf-alpine

# 作者
MAINTAINER ZHANHAIBIN

# 定义环境变量
ENV \
  CODE_HOME=home/code

# 创建数据文件夹
RUN mkdir -p ~/.m2/repository; 

COPY ./settings.xml ${MAVEN_HOME}/conf/


